SELECT COUNT(*)
FROM FILMS;

SELECT COUNT(F.CODFILM)
FROM FILMS F, REALISATEURS R, JOUENT J, ACTEURS A
WHERE F.CODREAL=R.CODREAL
  AND F.CODFILM=J.CODFILM
  AND J.NACT=A.CODACT
  AND R.NOMREAL='Cameron'
  AND A.SEXE='F'
  AND extract(year from A.DNAISSACT) > 1970;

SELECT COUNT(F.CODFILM)
FROM ACTEURS A, JOUENT J, FILMS F, REALISATEURS R
WHERE A.CODACT=J.NACT
  AND J.CODFILM=F.CODFILM
  AND R.CODREAL = F.CODREAL
  AND R.NOMREAL='Cameron';

SELECT MAX(BUDGET)
FROM FILMS;

SELECT TITREFILM
FROM FILMS
WHERE BUDGET = (SELECT MAX(BUDGET) 
                FROM FILMS);

SELECT SUM(F.BUDGET)
FROM FILMS F, REALISATEURS R
WHERE F.CODREAL=R.CODREAL
  AND R.NOMREAL='Cameron';


SELECT R.CODREAL, R.NOMREAL, COUNT(F.CODFILM)
FROM FILMS F, REALISATEURS R
WHERE F.CODREAL=R.CODREAL
GROUP BY R.CODREAL, R.NOMREAL;

SELECT R.NOMREAL, R.NATIONREAL, COUNT(DISTINCT J.NACT)
FROM REALISATEURS R, FILMS F, JOUENT J, ACTEURS A
WHERE R.CODREAL=F.CODREAL
  AND F.CODFILM=J.CODFILM
  AND A.CODACT=J.NACT
GROUP BY R.NOMREAL, R.NATIONREAL;

SELECT R.NOMREAL, R.NATIONREAL, SUM(F.BUDGET)
FROM REALISATEURS R, FILMS F
WHERE R.CODREAL=F.CODREAL
  AND F.CATFILM='science-fiction'
GROUP BY R.NOMREAL, R.NATIONREAL; 

SELECT R.NOMREAL, R.NATIONREAL
FROM REALISATEURS R, FILMS F
WHERE R.CODREAL=F.CODREAL
GROUP BY R.NOMREAL, R.NATIONREAL;