
SELECT * 
FROM FILMS F
WHERE F.BUDGET > 1000000;

SELECT R.*
FROM REALISATEURS R, FILMS F
WHERE F.TITREFILM='Ensemble c''est out'
  AND R.DDECREAL<F.DATESORTIE;

SELECT DISTINCT F.TITREFILM, R.NOMREAL
FROM FILMS F, REALISATEURS R, JOUENT J
WHERE J.NOMPERS='Lieutenant Ellen Ripley' 
  AND J.CODFILM=F.CODFILM
  AND R.CODREAL=F.CODREAL;

SELECT NOMREAL
FROM REALISATEURS
WHERE CODREAL NOT IN (SELECT CODREAL
                      FROM FILMS F, JOUENT J, ACTEURS A
                      WHERE F.CODFILM=J.CODFILM
                        AND J.NACT=A.CODACT
                        AND NATIONACT='américaine');
SELECT NOMREAL, CODREAL 
FROM REALISATEURS
WHERE CODREAL IN (SELECT CODREAL
                  FROM REALISATEURS
                  minus
                  SELECT CODREAL
                  FROM FILMS F, JOUENT J, ACTEURS A
                  WHERE F.CODFILM=J.CODFILM
                    AND J.NACT=A.CODACT
                    AND NATIONACT='américaine');


SELECT DISTINCT R.CODREAL, R.NOMREAL, R.PRENOMREAL
FROM REALISATEURS R, FILMS F, ACTEURS A, JOUENT J
WHERE (A.NATIONACT='americain' OR A.NATIONACT='americaine')
  AND A.CODACT!=J.NACT
  AND J.CODFILM=F.CODFILM 
  AND F.CODREAL=R.CODREAL;


SELECT F.TITREFILM, F.DATESORTIE, F.BUDGET
FROM FILMS F, REALISATEURS R
WHERE DATESORTIE-DNAISSREAL<40*365
  AND R.CODREAL=F.CODREAL;


SELECT DISTINCT NATIONACT
FROM ACTEURS;

SELECT NOMREAL, PRENOMREAL
FROM REALISATEURS
WHERE NATIONREAL='US' AND CODREAL NOT IN (SELECT CODREAL
                      FROM FILMS F, JOUENT J, ACTEURS A
                      WHERE F.CODFILM=J.CODFILM
                        AND J.NACT=A.CODACT
                        AND A.NATIONACT!='FR');
